language: node_js
node_js:
  - "6"

before_install:
  - npm install
  - npm run debug
  - sleep 3

script:
  - export DEBUG=TRUE
  - npm test
  - export DEBUG=FALSE
  - npm run migration
  - npm run generate
